baseurl = "https://agha.dev"
title = "Nour Agha"
theme = "hugo-coder"
languagecode = "en"
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true

[markup.highlight]
  noClasses = false

[params]
  author = "Nour Agha"
  info = ["Software Engineer"]
  description = "Computer engineer and software developer. Free and open source software (FOSS) enthusiast. Privacy, security, digital freedom and humane technology advocate. INFP, dreamer, writer and gamer. Progressive and uplifting electronic music listener, producer and DJ."
  images = ["images/cover.png"]
  keywords = "blog,developer,personal"
  avatarURL = "images/avatar.jpg"
  dateFormat = "January 2, 2006"
  since = 2022

  touchIcon = "images/apple-touch-icon.png"
  faviconSVG = "images/favicon.svg"
  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  maxSeeAlsoItems = 5
  rtl = false
  colorScheme = "auto"
  hideColorSchemeToggle = false

  customCSS = []
  customSCSS = []
  customJS = []
  customRemoteJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[permalinks]
  posts = "blog/:slug"

[params.giscus] # https://giscus.app
  repo = "nourkagha/agha.dev"
  repoID = "R_kgDOIVKGgw" 
  category = "Comments"
  categoryID = "DIC_kwDOIVKGg84CTIJ3"
  mapping = "pathname"
  term = ""
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = ""
  lang = "en"
  loading = ""

# Social links
[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:nour@agha.dev"
[[params.social]]
  name = "Signal"
  icon = "fa-brands fa-signal-messenger fa-2x"
  weight = 2
  url = "https://signal.agha.dev"
[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github fa-2x"
  weight = 3
  url = "https://github.agha.dev"
[[params.social]]
  name = "Mastodon"
  icon = "fa-brands fa-mastodon fa-2x"
  weight = 4
  url = "https://agha.dev/@nour"
  rel = "me"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 5
  url = "https://linkedin.agha.dev"
#[[params.social]]
#  name = "RSS"
#  icon = "fa fa-rss fa-2x"
#  weight = 6
#  url = "index.xml"
#  rel = "alternate"
#  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "blog"
[[menu.main]]
  name = "Contact"
  weight = 3
  url = "contact"
