baseurl = "https://agha.dev"
title = "Nour Agha"
theme = "hugo-coder"
languagecode = "en"
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true

[markup.highlight]
  style = "github-dark"

[params]
  author = "Nour Agha"
  info = ["Computer Engineer", "Software Developer"]
  description = "My personal website and blog."
  images = ["images/cover.png"]
  keywords = "blog,developer,personal"
  avatarURL = "images/avatar.jpg"
  dateFormat = "January 2, 2006"
  since = 2022

  touchIcon = "images/apple-touch-icon.png"  
  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  maxSeeAlsoItems = 5
  rtl = false
  colorScheme = "auto"
  hideColorSchemeToggle = false

  customCSS = []
  customSCSS = []
  customJS = []
  customRemoteJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[permalinks]
  posts = "blog/:slug"

[params.giscus] # https://giscus.app
  repo = "nourkagha/agha.dev"
  repoID = "R_kgDOIVKGgw" 
  category = "Comments"
  categoryID = "DIC_kwDOIVKGg84CTIJ3"
  mapping = "pathname"
  term = ""
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = ""
  lang = "en"
  loading = ""

# Social links
[[params.social]]
  name = "Mail"
  icon = "fa fa-2x fa-envelope"
  weight = 1
  url = "mailto:nour@agha.dev"
[[params.social]]
  name = "GitHub"
  icon = "fa fa-2x fa-github"
  weight = 2
  url = "https://github.agha.dev"
[[params.social]]
  name = "Matrix"
  icon = "fa fa-2x fa-matrix-org"
  weight = 3
  url = "https://matrix.agha.dev"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-2x fa-mastodon"
  weight = 4
  url = "https://agha.dev/@nour"
  rel = "me"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 5
  url = "https://linkedin.agha.dev"
[[params.social]]
  name = "GnuPG"
  icon = "fa fa-2x fa-gnupg"
  weight = 6
  url = "gpg"
#[[params.social]]
#  name = "RSS"
#  icon = "fa fa-2x fa-rss"
#  weight = 7
#  url = "index.xml"
#  rel = "alternate"
#  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "blog"
[[menu.main]]
  name = "Contact"
  weight = 3
  url = "contact"
