[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'; script-src 'self' 'sha256-zxs1Daokqx9WyeUOlq0+TKzxhPeGJxMTg1OJy0ZYjbw=' 'sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==' giscus.app analytics.eu.umami.is cdn.jsdelivr.net; style-src 'self' 'sha256-2ycMMPFUOnyA34Yg3+cS/BEKpCQBZ+CBs9yaEsIzN+E=' giscus.app fonts.googleapis.com cdn.jsdelivr.net; img-src 'self'; font-src 'self' fonts.gstatic.com cdn.jsdelivr.net; connect-src 'self' analytics.eu.umami.is; child-src 'self'; frame-src 'self' giscus.app youtube-nocookie.com; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests; base-uri 'self'; manifest-src 'self'; report-uri https://nour.report-uri.com/r/d/csp/enforce"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), midi=(), notifications=(), push=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=(), payment=()"

[[redirects]]
  from = "https://nouragha.netlify.app/*"
  to = "https://agha.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://nour.agha.dev/*"
  to = "https://agha.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://about.agha.dev/*"
  to = "https://agha.dev/about"
  status = 301
  force = true

[[redirects]]
  from = "https://blog.agha.dev/*"
  to = "https://agha.dev/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://contact.agha.dev/*"
  to = "https://agha.dev/contact"
  status = 301
  force = true

[[redirects]]
  from = "/@nour/*"
  to = "https://fosstodon.org/@Nour/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/id/openpgp/*"
  to = "https://keyoxide.org/openpgp4fpr:135F691534C8919295ED97C1C1859ED057E714DC"
  status = 302
  force = true
  
[[redirects]]
  from = "/id/asp/*"
  to = "https://keyoxide.org/aspe:keyoxide.org:NRWOOGRSUA5JACMIMCVAQP4H6E"
  status = 302
  force = true

[[redirects]]
  from = "/id/*"
  to = "/contact/#identity"
  status = 302
  force = true

[[redirects]]
  from = "https://github.agha.dev/*"
  to = "https://github.com/nourkagha/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://linkedin.agha.dev/*"
  to = "https://linkedin.com/in/nouragha"
  status = 302
  force = true

[[redirects]]
  from = "https://links.agha.dev/*"
  to = "https://nour.lol"
  status = 302
  force = true

[[redirects]]
  from = "https://mastodon.agha.dev/*"
  to = "https://fosstodon.org/@Nour/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://matrix.agha.dev/*"
  to = "https://matrix.to/#/@nour:mozilla.org"
  status = 302
  force = true

[[redirects]]
  from = "https://pixelfed.agha.dev/*"
  to = "https://pixelfed.social/@Nour/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://signal.agha.dev/*"
  to = "https://signal.me/#eu/kG31MsSYsHuTUB9uACZVMuqt6Up-5t5rJxEZLAdOU2uaR2GpAfROUriQiLgAmVaX"
  status = 302
  force = true

[[redirects]]
  from = "/rss"
  to = "/index.xml"
  status = 301
  force = true

[[redirects]]
  from = "https://analytics.agha.dev/*"
  to = "https://analytics.umami.is/share/Xsx2krfZC7YHC6zK/Nour%20Agha"
  status = 302
  force = true

[[redirects]]
  from = "https://status.agha.dev/*"
  to = "https://stats.uptimerobot.com/Q8KKEHXGK1"
  status = 302
  force = true

[[redirects]]
  from = "https://mta-sts.agha.dev/.well-known/mta-sts.txt"
  to = "https://agha.dev/.well-known/mta-sts.txt"
  status = 200

[[redirects]]
  from = "https://mta-sts.agha.dev/*"
  to = "https://mta-sts.agha.dev/.well-known/mta-sts.txt"
  status = 302
  force = true

[[redirects]]
  from = "https://nouragha.com/*"
  to = "https://agha.dev/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://www.nouragha.com/*"
  to = "https://www.agha.dev/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://about.nouragha.com/*"
  to = "https://about.agha.dev"
  status = 302
  force = true

[[redirects]]
  from = "https://blog.nouragha.com/*"
  to = "https://blog.agha.dev/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://contact.nouragha.com/*"
  to = "https://contact.agha.dev"
  status = 302
  force = true

[[redirects]]
  from = "https://links.nouragha.com/*"
  to = "https://links.agha.dev"
  status = 302
  force = true

[[redirects]]
  from = "https://mta-sts.nouragha.com/.well-known/mta-sts.txt"
  to = "https://agha.dev/.well-known/mta-sts.txt"
  status = 200

[[redirects]]
  from = "https://mta-sts.nouragha.com/*"
  to = "https://mta-sts.nouragha.com/.well-known/mta-sts.txt"
  status = 302
  force = true
