[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' https://fonts.googleapis.com, https://cdn.jsdelivr.net; img-src 'self'; font-src 'self' https://fonts.gstatic.com, https://cdn.jsdelivr.net; connect-src 'self'; child-src 'self'; frame-src 'self' https://youtube-nocookie.com; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests; block-all-mixed-content; base-uri 'self'; report-uri https://nour.report-uri.com/r/d/csp/enforce"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), midi=(), notifications=(), push=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=(), payment=()"
    
[[redirects]]
  from = "https://nouragha.netlify.app"
  to = "https://agha.dev"
  status = 301
  force = true

[[redirects]]
  from = "/@nour"
  to = "https://fosstodon.org/@Nour"
  status = 302
  force = true
