[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' https://fonts.googleapis.com, https://cdn.jsdelivr.net; img-src 'self'; font-src 'self' https://fonts.gstatic.com, https://cdn.jsdelivr.net; connect-src 'self'; child-src 'self'; frame-src 'self' https://youtube-nocookie.com; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests; block-all-mixed-content; base-uri 'self'; report-uri https://nour.report-uri.com/r/d/csp/enforce"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), midi=(), notifications=(), push=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=(), payment=()"

[[redirects]]
  from = "https://nouragha.netlify.app/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://nour.agha.dev/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://about.agha.dev"
  to = "/about"
  status = 301

[[redirects]]
  from = "https://blog.agha.dev/*"
  to = "/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://contact.agha.dev"
  to = "/contact"
  status = 301

[[redirects]]
  from = "/@nour/*"
  to = "https://fosstodon.org/@Nour/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://github.agha.dev/*"
  to = "https://github.com/nourkagha/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://keyoxide.agha.dev"
  to = "https://keyoxide.org/nour@agha.dev"
  status = 302

[[redirects]]
  from = "https://linkedin.agha.dev"
  to = "https://linkedin.com/in/nouragha"
  status = 302

[[redirects]]
  from = "https://links.agha.dev"
  to = "https://nour.omg.lol"
  status = 302

[[redirects]]
  from = "https://mastodon.agha.dev/*"
  to = "https://fosstodon.org/@Nour/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://matrix.agha.dev"
  to = "https://matrix.to/#/@nour:mozilla.org"
  status = 302

[[redirects]]
  from = "https://pixelfed.agha.dev/*"
  to = "https://pixelfed.social/@Nour/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://mta-sts.agha.dev/.well-known/mta-sts.txt"
  to = "/.well-known/mta-sts.txt"
  status = 200

[[redirects]]
  from = "https://mta-sts.agha.dev"
  to = "https://agha.dev"
  status = 302

[[redirects]]
  from = "https://nouragha.com/*"
  to = "/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://www.nouragha.com/*"
  to = "/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://about.nouragha.com"
  to = "/about"
  status = 302

[[redirects]]
  from = "https://blog.nouragha.com/*"
  to = "/blog/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://contact.nouragha.com"
  to = "/contact"
  status = 302

[[redirects]]
  from = "https://mta-sts.nouragha.com/.well-known/mta-sts.txt"
  to = "/.well-known/mta-sts.txt"
  status = 200

[[redirects]]
  from = "https://mta-sts.nouragha.com"
  to = "https://nouragha.com"
  status = 302
